# Generated by Django 3.2.3 on 2021-05-24 18:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_tarea_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='dia',
            field=models.DateField(default=datetime.datetime(2021, 5, 24, 18, 49, 56, 744306, tzinfo=utc)),
        ),
    ]
