# Generated by Django 3.2.3 on 2021-05-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_tarea_dia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='horario',
            new_name='hora',
        ),
    ]
