# Generated by Django 3.2.3 on 2021-05-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_horario_tarea_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='dia',
            new_name='fecha',
        ),
    ]
