# Generated by Django 3.2.3 on 2021-05-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_dia_tarea_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='fecha',
            new_name='dia',
        ),
    ]
