# Generated by Django 3.2.3 on 2021-05-27 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_fecha_tarea_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='dia',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
