# Generated by Django 3.2.3 on 2023-09-02 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_tarea_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=140)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
